- name: "Install Nginx"
  hosts: servers
  become: true
  tasks:
    - name: Epel CentOS
      package:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Nginx
      ansible.builtin.package:
        name: nginx
        state: latest
